# -*- coding: utf-8 -*-
"""atm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxjalXVonjv63t8fB7PqSJp_akHcJebW
"""

balance = 0

def deposit():
    global balance
    amt = float(input("Amount to deposit: "))
    balance += amt

def withdraw():
    global balance
    amt = float(input("Amount to withdraw: "))
    if amt <= balance:
        balance -= amt
    else:
        print("Not enough balance")

def check_balance():
    print("Balance:", balance)

deposit()
withdraw()
check_balance()