# -*- coding: utf-8 -*-
"""bill splitter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J_IOCfCa5lhfoK-7g7an-Il7PIYprCMy
"""

bill = float(input("Enter bill amount: "))
people = int(input("People sharing: "))
tip = float(input("Tip %: "))

total = bill + (bill * tip / 100)
print("Each person pays:", round(total / people, 2))