# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4RZ_DDFAdygEp00wTYzWnfgPO7K_rCN
"""

a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
op = input("Enter operation (+, -, *, /): ")

if op == '+':
    print("Result:", a + b)
elif op == '-':
    print("Result:", a - b)
elif op == '*':
    print("Result:", a * b)
elif op == '/':
    if b != 0:
        print("Result:", a / b)
    else:
        print("Cannot divide by zero")
else:
    print("Invalid operation")