# -*- coding: utf-8 -*-
"""Countdown timer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxWcjfvspswFvX4yI44jaNCn2m1aMrsM
"""

import time

sec = int(input("Enter time in seconds: "))
while sec > 0:
    print(sec)
    time.sleep(1)
    sec -= 1

print("Time's up!")