# -*- coding: utf-8 -*-
"""number guessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-rjCUnuji1kjFubvFibnXYYx5US9B1B
"""

import random
number = random.randint(1, 10)

guess = int(input("Guess a number (1-10): "))

if guess == number:
    print("Correct!")
else:
    print("Wrong! The number was", number)