# -*- coding: utf-8 -*-
"""password generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBI5qOIRdp1hKgnxEIzrL9lfTZqKahez
"""

import random
import string

length = int(input("Enter password length: "))
characters = string.ascii_letters + string.digits
password = ''.join(random.choice(characters) for i in range(length))
print("Password:", password)