# -*- coding: utf-8 -*-
"""remainder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bFCYuFKnXtcR2ML4CL28qsOi3gdFpGn9
"""

import time

msg = input("Enter reminder message: ")
sec = int(input("Remind after how many seconds: "))

time.sleep(sec)
print("Reminder:", msg)